const path = require('path')
require('dotenv').config()
const express = require('express')
const http = require('http')
const multer = require('multer')
const helmet = require('helmet')
const compression = require('compression')
const cors = require('cors')
const morgan = require('morgan')
const { init, emitDataRefresh } = require('./services/realtime')
const checkPassword = require('./middlewares/checkPassword')
const error = require('./middlewares/error')
const apiRoutes = require('./routes/api')
const adminRoutes = require('./routes/admin')
const { ensureSchema } = require('./db/init')
const app = express()
app.use(express.json({ limit: '1mb' }))
app.use(express.urlencoded({ extended: true }))
app.use(helmet())
app.use(compression())
app.use(cors())
app.use(morgan('tiny'))
app.use(express.static(path.join(__dirname, '..', 'public')))
const upload = multer({ storage: multer.memoryStorage() })
app.post('/admin/upload-excel', upload.single('file'), checkPassword, async (req, res, next) => {
  try {
    const tableId = req.body.table_id ? Number(req.body.table_id) : null
    const { upsertExcel } = require('./services/excel')
    const { getPool } = require('./db/pool')
    if (!req.file || !req.file.buffer) return res.status(400).json({ error: 'Arquivo ausente' })
    const result = await upsertExcel(req.file.buffer, tableId)
    const pool = getPool()
    await pool.query('INSERT INTO logs (table_id, action_type, details) VALUES (?,?,?)', [tableId, 'EXCEL_UPLOAD', JSON.stringify(result)])
    emitDataRefresh({ reason: 'excel' })
    res.json(result)
  } catch (e) { next(e) }
})
app.use('/api', apiRoutes)
app.use('/admin', adminRoutes)
app.use(error)
;(async function(){
  await ensureSchema()
  const server = http.createServer(app)
  const io = require('socket.io')(server, { cors: { origin: '*' } })
  init(io)
  const port = process.env.PORT || 3000
  server.listen(port, () => {
    console.log(`Server listening at http://localhost:${port}`)
  })
})()
