CREATE TABLE IF NOT EXISTS tables (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  session_key VARCHAR(255) UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  table_id INT,
  serie VARCHAR(50) NOT NULL,
  aluno VARCHAR(255) NOT NULL,
  mesa VARCHAR(50) NOT NULL,
  veio TINYINT(1) DEFAULT 0,
  chamado TINYINT(1) DEFAULT 0,
  produtos TEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  unique_key VARCHAR(255) UNIQUE,
  INDEX idx_records_serie (serie),
  FOREIGN KEY (table_id) REFERENCES tables(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  record_id INT,
  table_id INT,
  action_type VARCHAR(50) NOT NULL,
  details JSON,
  changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (record_id) REFERENCES records(id) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (table_id) REFERENCES tables(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS station_roles (
  table_id INT PRIMARY KEY,
  role VARCHAR(20) NOT NULL,
  FOREIGN KEY (table_id) REFERENCES tables(id) ON DELETE CASCADE ON UPDATE CASCADE
);
